version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - bridge
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    volumes:
      - mongodb-data:/data/db
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    networks:
      - bridge
    restart: unless-stopped

volumes:
  mongodb-data:
    name: mongodb-data

networks:
  bridge:
    driver: bridge